http:
  middlewares:
    rate-limit-redis:
      rateLimit:
        average: 70
        period: 1s
        burst: 100 # Pequeño pico de 100.
        redis:
          endpoints:
            - "redis:6379"

    cb-documents:
      circuitBreaker:
        # Abre el circuito si el 50% de las peticiones tarda más de 100ms
        expression: "ResponseCodeRatio(500, 600, 0, 600) > 0.25 || LatencyAtQuantileMS(50.0) > 200"
        # O si el 25% de las respuestas son errores 5xx